// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using jupter_server.Helpers;

#nullable disable

namespace jupter_server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251214020818_dev02.3")]
    partial class dev023
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("jupter_server.Entities.AlbumImageInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlbumImageListInfoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<string>("src")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("AlbumImageListInfoId");

                    b.HasIndex("sequence");

                    b.ToTable("AlbumImageInfo");
                });

            modelBuilder.Entity("jupter_server.Entities.AlbumImageListInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ThemeAlbumInfoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ThemeAlbumInfoId");

                    b.HasIndex("sequence");

                    b.ToTable("AlbumImageListInfo");
                });

            modelBuilder.Entity("jupter_server.Entities.Gallery", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("backgroundImage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("Gallery");

                    b.HasData(
                        new
                        {
                            id = new Guid("630e5ef0-cf44-4b82-b4e1-9838cee24e4d"),
                            isValid = true,
                            name = "gallery_1"
                        });
                });

            modelBuilder.Entity("jupter_server.Entities.GalleryThemeInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GalleryId")
                        .HasColumnType("uuid");

                    b.Property<string>("coverImage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("GalleryId");

                    b.HasIndex("sequence");

                    b.ToTable("GalleryThemeInfo");
                });

            modelBuilder.Entity("jupter_server.Entities.Item", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("detail")
                        .HasColumnType("text");

                    b.Property<string>("imgSrc")
                        .HasColumnType("text");

                    b.Property<string>("includings")
                        .HasColumnType("text");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("jupter_server.Entities.Order", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("bookingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<int?>("photoAmount")
                        .HasColumnType("integer");

                    b.Property<string>("postscript")
                        .HasColumnType("text");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<string>("session")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("jupter_server.Entities.ThemeAlbumInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GalleryThemeInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("coverImage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("GalleryThemeInfoId");

                    b.HasIndex("sequence");

                    b.ToTable("ThemeAlbumInfo");
                });

            modelBuilder.Entity("jupter_server.Entities.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("dateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("interest")
                        .HasColumnType("text");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("email");

                    b.ToTable("User");
                });

            modelBuilder.Entity("jupter_server.Entities.AlbumImageInfo", b =>
                {
                    b.HasOne("jupter_server.Entities.AlbumImageListInfo", "AlbumImageListInfo")
                        .WithMany("AlbumImageInfos")
                        .HasForeignKey("AlbumImageListInfoId");

                    b.Navigation("AlbumImageListInfo");
                });

            modelBuilder.Entity("jupter_server.Entities.AlbumImageListInfo", b =>
                {
                    b.HasOne("jupter_server.Entities.ThemeAlbumInfo", "ThemeAlbumInfo")
                        .WithMany("AlbumImageListInfos")
                        .HasForeignKey("ThemeAlbumInfoId");

                    b.Navigation("ThemeAlbumInfo");
                });

            modelBuilder.Entity("jupter_server.Entities.GalleryThemeInfo", b =>
                {
                    b.HasOne("jupter_server.Entities.Gallery", "Gallery")
                        .WithMany("ThemeInfos")
                        .HasForeignKey("GalleryId");

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("jupter_server.Entities.Order", b =>
                {
                    b.HasOne("jupter_server.Entities.Item", "Item")
                        .WithMany("Orders")
                        .HasForeignKey("ItemId");

                    b.HasOne("jupter_server.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("jupter_server.Entities.ThemeAlbumInfo", b =>
                {
                    b.HasOne("jupter_server.Entities.GalleryThemeInfo", "GalleryThemeInfo")
                        .WithMany("ThemeAlbumInfos")
                        .HasForeignKey("GalleryThemeInfoId");

                    b.Navigation("GalleryThemeInfo");
                });

            modelBuilder.Entity("jupter_server.Entities.AlbumImageListInfo", b =>
                {
                    b.Navigation("AlbumImageInfos");
                });

            modelBuilder.Entity("jupter_server.Entities.Gallery", b =>
                {
                    b.Navigation("ThemeInfos");
                });

            modelBuilder.Entity("jupter_server.Entities.GalleryThemeInfo", b =>
                {
                    b.Navigation("ThemeAlbumInfos");
                });

            modelBuilder.Entity("jupter_server.Entities.Item", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("jupter_server.Entities.ThemeAlbumInfo", b =>
                {
                    b.Navigation("AlbumImageListInfos");
                });

            modelBuilder.Entity("jupter_server.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
