// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using jupter_server.Helpers;

#nullable disable

namespace jupter_server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251225233607_dev02.6")]
    partial class dev026
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("jupter_server.Entities.AlbumImageInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlbumImageListInfoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<string>("src")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("AlbumImageListInfoId");

                    b.HasIndex("sequence");

                    b.ToTable("AlbumImageInfo");
                });

            modelBuilder.Entity("jupter_server.Entities.AlbumImageListInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ThemeAlbumInfoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ThemeAlbumInfoId");

                    b.HasIndex("sequence");

                    b.ToTable("AlbumImageListInfo");
                });

            modelBuilder.Entity("jupter_server.Entities.Gallery", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("backgroundImage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("name");

                    b.ToTable("Gallery");

                    b.HasData(
                        new
                        {
                            id = new Guid("630e5ef0-cf44-4b82-b4e1-9838cee24e4d"),
                            isValid = true,
                            name = "gallery_1"
                        });
                });

            modelBuilder.Entity("jupter_server.Entities.GalleryThemeInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GalleryId")
                        .HasColumnType("uuid");

                    b.Property<string>("coverImage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("GalleryId");

                    b.HasIndex("sequence");

                    b.ToTable("GalleryThemeInfo");

                    b.HasData(
                        new
                        {
                            id = new Guid("ba11a7ef-ddcb-4545-a40a-fc3262801f96"),
                            GalleryId = new Guid("630e5ef0-cf44-4b82-b4e1-9838cee24e4d"),
                            coverImage = "",
                            description = "this is nature theme",
                            isValid = true,
                            sequence = 1,
                            title = "NATURE"
                        },
                        new
                        {
                            id = new Guid("56bbe3de-8d3f-4630-b0c1-21a49c64c97b"),
                            GalleryId = new Guid("630e5ef0-cf44-4b82-b4e1-9838cee24e4d"),
                            coverImage = "",
                            description = "this is character theme",
                            isValid = true,
                            sequence = 2,
                            title = "CHARACTER"
                        },
                        new
                        {
                            id = new Guid("1b56daf8-2992-479f-acec-c34838c91898"),
                            GalleryId = new Guid("630e5ef0-cf44-4b82-b4e1-9838cee24e4d"),
                            coverImage = "",
                            description = "this is event theme",
                            isValid = true,
                            sequence = 3,
                            title = "EVENT"
                        },
                        new
                        {
                            id = new Guid("9f45fc55-2d8f-4008-a4ec-f6526ef280e1"),
                            GalleryId = new Guid("630e5ef0-cf44-4b82-b4e1-9838cee24e4d"),
                            coverImage = "",
                            description = "this is business theme",
                            isValid = true,
                            sequence = 4,
                            title = "BUSINESS"
                        });
                });

            modelBuilder.Entity("jupter_server.Entities.Item", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("detail")
                        .HasColumnType("text");

                    b.Property<string>("imgSrc")
                        .HasColumnType("text");

                    b.Property<string>("includings")
                        .HasColumnType("text");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("jupter_server.Entities.Order", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("bookingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<int?>("photoAmount")
                        .HasColumnType("integer");

                    b.Property<string>("postscript")
                        .HasColumnType("text");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<string>("session")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("jupter_server.Entities.ThemeAlbumInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GalleryThemeInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("coverImage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("GalleryThemeInfoId");

                    b.HasIndex("sequence");

                    b.ToTable("ThemeAlbumInfo");

                    b.HasData(
                        new
                        {
                            id = new Guid("061e7679-87da-4e4d-b516-dbb2443671a2"),
                            GalleryThemeInfoId = new Guid("ba11a7ef-ddcb-4545-a40a-fc3262801f96"),
                            isValid = true,
                            sequence = 1,
                            title = "Album_1"
                        },
                        new
                        {
                            id = new Guid("a0331524-0418-439f-baf2-e783c26dcb04"),
                            GalleryThemeInfoId = new Guid("ba11a7ef-ddcb-4545-a40a-fc3262801f96"),
                            isValid = true,
                            sequence = 2,
                            title = "Album_2"
                        },
                        new
                        {
                            id = new Guid("5af125aa-0eeb-4c01-95e9-e89d9268771e"),
                            GalleryThemeInfoId = new Guid("56bbe3de-8d3f-4630-b0c1-21a49c64c97b"),
                            isValid = true,
                            sequence = 3,
                            title = "Album_3"
                        },
                        new
                        {
                            id = new Guid("77a70ce5-e14f-4039-9df1-27c5ff0b605f"),
                            GalleryThemeInfoId = new Guid("1b56daf8-2992-479f-acec-c34838c91898"),
                            isValid = true,
                            sequence = 4,
                            title = "Album_4"
                        },
                        new
                        {
                            id = new Guid("adfa6ea8-2b61-487c-bf4c-a98eaa0b7f13"),
                            GalleryThemeInfoId = new Guid("9f45fc55-2d8f-4008-a4ec-f6526ef280e1"),
                            isValid = true,
                            sequence = 5,
                            title = "Album_5"
                        },
                        new
                        {
                            id = new Guid("41aec750-9233-4cb8-ace2-88f92a11a28c"),
                            GalleryThemeInfoId = new Guid("9f45fc55-2d8f-4008-a4ec-f6526ef280e1"),
                            isValid = true,
                            sequence = 6,
                            title = "Album_6"
                        });
                });

            modelBuilder.Entity("jupter_server.Entities.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("dateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("interest")
                        .HasColumnType("text");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("reserve")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("email");

                    b.ToTable("User");
                });

            modelBuilder.Entity("jupter_server.Entities.AlbumImageInfo", b =>
                {
                    b.HasOne("jupter_server.Entities.AlbumImageListInfo", "AlbumImageListInfo")
                        .WithMany("AlbumImageInfos")
                        .HasForeignKey("AlbumImageListInfoId");

                    b.Navigation("AlbumImageListInfo");
                });

            modelBuilder.Entity("jupter_server.Entities.AlbumImageListInfo", b =>
                {
                    b.HasOne("jupter_server.Entities.ThemeAlbumInfo", "ThemeAlbumInfo")
                        .WithMany("AlbumImageListInfos")
                        .HasForeignKey("ThemeAlbumInfoId");

                    b.Navigation("ThemeAlbumInfo");
                });

            modelBuilder.Entity("jupter_server.Entities.GalleryThemeInfo", b =>
                {
                    b.HasOne("jupter_server.Entities.Gallery", "Gallery")
                        .WithMany("ThemeInfos")
                        .HasForeignKey("GalleryId");

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("jupter_server.Entities.Order", b =>
                {
                    b.HasOne("jupter_server.Entities.Item", "Item")
                        .WithMany("Orders")
                        .HasForeignKey("ItemId");

                    b.HasOne("jupter_server.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("jupter_server.Entities.ThemeAlbumInfo", b =>
                {
                    b.HasOne("jupter_server.Entities.GalleryThemeInfo", "GalleryThemeInfo")
                        .WithMany("ThemeAlbumInfos")
                        .HasForeignKey("GalleryThemeInfoId");

                    b.Navigation("GalleryThemeInfo");
                });

            modelBuilder.Entity("jupter_server.Entities.AlbumImageListInfo", b =>
                {
                    b.Navigation("AlbumImageInfos");
                });

            modelBuilder.Entity("jupter_server.Entities.Gallery", b =>
                {
                    b.Navigation("ThemeInfos");
                });

            modelBuilder.Entity("jupter_server.Entities.GalleryThemeInfo", b =>
                {
                    b.Navigation("ThemeAlbumInfos");
                });

            modelBuilder.Entity("jupter_server.Entities.Item", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("jupter_server.Entities.ThemeAlbumInfo", b =>
                {
                    b.Navigation("AlbumImageListInfos");
                });

            modelBuilder.Entity("jupter_server.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
